#!/bin/python
import os

import japonicus
import evaluation
os.chdir(os.path.dirname(os.path.realpath(__file__)))


settings, options = japonicus.buildSettingsOptions(
    japonicus.options.parser,
    evaluation.gekko.SettingsFiles
)
japonicus.JaponicusSession(evaluation.gekko, settings, options)
