#!/bin/python
import os

import japonicus

os.chdir(os.path.dirname(os.path.realpath(__file__)))


settings, options = japonicus.buildJaponicusOptions(japonicus.options.parser)
japonicus.launchJaponicus(settings, options)
